pipeline:
  name: harness-datetime-service
  identifier: harnessdatetimeservice
  projectIdentifier: AJPahl_Sandbox
  orgIdentifier: sandbox
  tags:
    MODERN: "true"
  properties:
    ci:
      codebase:
        connectorRef: ajgithubconnector
        repoName: harness-datetime-service
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: false
          buildIntelligence:
            enabled: true
          execution:
            steps:
              - stepGroup:
                  name: Build-Test
                  identifier: BuildTest
                  steps:
                    - parallel:
                        - step:
                            type: Run
                            name: RunNoTests
                            identifier: build_jar
                            spec:
                              connectorRef: dockerHub
                              image: gradle:8.14-jdk21-jammy
                              shell: Bash
                              command: gradle build -x test
                              imagePullPolicy: IfNotPresent
                        - step:
                            type: Test
                            name: RunWithTests
                            identifier: Test_1
                            spec:
                              shell: Sh
                              command: gradle build
                              intelligenceMode: true
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: dockerHub
                    repo: ajpahl1008/harness-datetime-service
                    tags:
                      - 1.<+pipeline.sequenceId>
                    caching: true
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
