apiVersion: v1
kind: Service
metadata:
  name: harness-datetime-service-deployment-service
  namespace: aj
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: harness-datetime-service-deployment
