apiVersion: v1
kind: Namespace
metadata:
  name: rockwad
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-datetime-service-deployment
  namespace: rockwad
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harness-datetime-service-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: harness-datetime-service-deployment
    spec:
      containers:
      - name: harness-datetime-service
        image: {{.Values.image}}
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
